name: Deploy Quizzes to S3
on:
  push:
    branches: ["main"]
    paths: ["quizzes/**"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync quizzes
        run: aws s3 sync quizzes/ s3://s3quizesbucket/quiz-content/ --delete
