name: Deploy Infra and Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Frontend build ---
      - name: Clean install dependencies (frontend)
        working-directory: frontend
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Compute frontend dist hash
        working-directory: frontend
        id: hash
        run: |
          # compute a deterministic hash of the built files
          find dist -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}' > deploy-hash.txt
          echo "DEPLOY_HASH=$(cat deploy-hash.txt)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build Lambda
        run: |
          cd infra/lambda/list-subjects
          npm install
         # npm run build

      # --- Infra deploy ---
      - name: Clean install dependencies (infra)
        working-directory: infra
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: CDK Deploy
        working-directory: infra
        run: |
          npx cdk deploy --require-approval never -c deployHash=${{ steps.hash.outputs.DEPLOY_HASH }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
