name: Deploy Infra and Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # --- Frontend build ---
      - name: Clean install dependencies (frontend)
        working-directory: frontend
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Build Lambda
        run: |
          cd lambda/list-subjects
          npm ci
          npm run build

      # --- Infra deploy ---
      - name: Clean install dependencies (infra)
        working-directory: infra
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: CDK Deploy
        working-directory: infra
        run: npx cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
